name: Benchmark

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
        sudo dpkg -i hyperfine_1.9.0_amd64.deb
        sudo apt install texlive-full pandoc --fix-missing
    - name: Benchmark point against pandoc beamer
      run: ./benchmark.sh
